// src/lib/github.ts
//
// GitHub integration for the production pipeline.
// Creates repos and pushes code using the GitHub REST API + git CLI.

import { execSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import path from 'node:path'

const GITHUB_API = 'https://api.github.com'

/**
 * Sanitize a card title into a valid GitHub repo name.
 * - Lowercase
 * - Replace spaces and special chars with hyphens
 * - Remove consecutive hyphens
 * - Trim leading/trailing hyphens
 */
export function toRepoName(title: string): string {
  return title
    .toLowerCase()
    .replace(/[äå]/g, 'a')
    .replace(/ö/g, 'o')
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || 'project'
}

/**
 * Create a GitHub repository via the REST API.
 * Returns the clone URL (https).
 * If the repo already exists, returns its URL.
 *
 * Requires GITHUB_TOKEN env var.
 */
export async function createGitHubRepo(repoName: string): Promise<string> {
  const token = process.env.GITHUB_TOKEN
  if (!token) {
    throw new Error('GITHUB_TOKEN ei ole asetettu — GitHub-integraatio ei toimi')
  }

  // First, check if repo already exists
  const owner = await getGitHubOwner()
  const checkRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  })

  if (checkRes.ok) {
    const existing = await checkRes.json() as { html_url: string }
    return existing.html_url
  }

  // Create new repo
  const createRes = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      description: `Auto-generated by TaskBoard pipeline`,
      private: false,
      auto_init: false,
    }),
  })

  if (!createRes.ok) {
    const err = await createRes.text()
    throw new Error(`GitHub repo luonti epäonnistui (${createRes.status}): ${err}`)
  }

  const repo = await createRes.json() as { html_url: string }
  return repo.html_url
}

/**
 * Get the GitHub owner (user/org) from GITHUB_TOKEN.
 * Caches the result for the process lifetime.
 */
let _cachedOwner: string | null = null

export async function getGitHubOwner(): Promise<string> {
  if (_cachedOwner) return _cachedOwner

  const token = process.env.GITHUB_TOKEN
  if (!token) throw new Error('GITHUB_TOKEN puuttuu')

  const res = await fetch(`${GITHUB_API}/user`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  })

  if (!res.ok) throw new Error('GitHub-käyttäjän haku epäonnistui')

  const user = await res.json() as { login: string }
  _cachedOwner = user.login
  return user.login
}

/**
 * Initialize git in workspace, commit all files, and push to GitHub.
 * Sets up git config, creates initial commit, and pushes.
 *
 * @returns The GitHub repo URL
 */
export async function gitInitAndPush(
  workspacePath: string,
  repoName: string,
): Promise<string> {
  const token = process.env.GITHUB_TOKEN
  if (!token) {
    throw new Error('GITHUB_TOKEN ei ole asetettu')
  }

  const owner = await getGitHubOwner()

  // Create default .gitignore if one doesn't exist
  const gitignorePath = path.join(workspacePath, '.gitignore')
  if (!existsSync(gitignorePath)) {
    execSync('echo "node_modules/\n.env\ndist/\n.next/\n*.log" > .gitignore', {
      cwd: workspacePath,
    })
  }

  // Configure git in workspace
  const gitExec = (cmd: string) =>
    execSync(cmd, {
      cwd: workspacePath,
      timeout: 30000,
      env: {
        ...process.env,
        GIT_TERMINAL_PROMPT: '0',
      },
    }).toString().trim()

  // Initialize git if not already initialized
  if (!existsSync(path.join(workspacePath, '.git'))) {
    gitExec('git init')
  }

  gitExec('git config user.name "TaskBoard Pipeline"')
  gitExec('git config user.email "pipeline@taskboard.local"')

  // Stage all files
  gitExec('git add -A')

  // Check if there's anything to commit
  try {
    gitExec('git diff --cached --quiet')
    // No changes — already committed
  } catch {
    // There are staged changes — commit them
    gitExec('git commit -m "Auto-commit by TaskBoard pipeline"')
  }

  // Create the GitHub repo
  const repoUrl = await createGitHubRepo(repoName)

  // Set remote and push (using token for auth)
  const remoteUrl = `https://${token}@github.com/${owner}/${repoName}.git`

  try {
    gitExec('git remote remove origin')
  } catch {
    // No remote yet — that's fine
  }
  gitExec(`git remote add origin ${remoteUrl}`)
  gitExec('git branch -M main')

  try {
    gitExec('git push -u origin main --force')
  } catch (err) {
    console.error('[GitHub] Push epäonnistui:', err)
    throw new Error('Git push epäonnistui — tarkista GITHUB_TOKEN oikeudet')
  }

  return repoUrl
}
